# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Import GPG Public Key
      run: |
        gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys EF80A866B47A981F
    
    - name: Use ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
                  
    - name: Set up Swift
      uses: SwiftyLab/setup-swift@latest
    
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
