# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Import GPG Public Key
      run: |
        echo "${{ secrets.GPG_PUBLIC_KEY }}" | gpg --import
      env:
        GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}

    - name: Set up Swift
      uses: SwiftyLab/setup-swift@latest
    
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
